# Generated by Django 2.2.5 on 2020-11-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avater',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
