# Generated by Django 2.2.5 on 2020-11-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20201114_1529'),
        ('lists', '0004_auto_20201114_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='rooms',
        ),
        migrations.AddField(
            model_name='list',
            name='rooms',
            field=models.ManyToManyField(related_name='lists', to='rooms.Room'),
        ),
    ]
